Add : Profile UploadView
wecode-bootcamp-korea/20-2nd-BeerBnB-backend pull request #9
Opened 2021-05-28 12:21 UTC by Action2theFuture

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- s3를 통한 profile upload
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [ ] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-05-31 01:53 UTC, redsaumon commented
커밋메세지는 어떤 작업을 했는지 알아볼 수 있어야합니다. 간략하게 적어주신 것은 좋으나, 제 3자가 한 눈에 파악하기 어려워보입니다. 다음부터는 신경써주세요.

2021-05-31 14:39 UTC, Action2theFuture commented
파일 업로드에 대한 unit test 접근하는 방식을 알려주세요

2021-06-01 08:46 UTC, lordmyshepherd requested changes

2021-06-01 08:46 UTC, lordmyshepherd commented on user/views.py
> +            file_urls = f"https://{AWS_S3_CUSTOM_DOMAIN}/profile/{file.name}"
file을 s3 bucket에 저장할 때, file이름이 중복되는 경우에는 어떻게 되나요?

2021-06-01 08:46 UTC, lordmyshepherd commented on user/views.py
> +            return JsonResponse({'massege':'create'}, status=200)
update_or_create을 사용하신 이유가 혹시 있으신가요?
profile_url이 달라지면 User를 하나 더 생성하는 건가요?

2021-06-01 08:46 UTC, lordmyshepherd commented on user/views.py
> +            )
잘 작성해주셨네요!!
작성해주신 코드처럼 `post(handler method)` 안에서 전부 구현할 수 도 있지만, wrapper class를 활용해서 좀더 객체지향 프로그래밍적으로 접근할 수 있을 것 같아요~

```python
class S3Client:
    def __init__(self, s3_client):
        self.s3_client = s3_client
        
    def upload(self, file):
        return ...
```

**In View**
```python
client = boto3.client(
    's3',
    aws_access_key_id = my_settings.AWS_S3_ACCESS_KEY_ID,
    aws_secret_access_key = my_settings.AWS_S3_SECRET_ACCESS_KEY
)

class Proflie(View):
    def post(self, request):
        s3_client = S3Client(client)
        ...
```
이렇게 작성하게 되면 테스트할 때 mocking하기 쉽고, 실제 기능을 가지고 있는 객체를 포장지처럼 한번 더 감싸서, 실제 기능을 담당하는 객체가 변경되도 호출자가 사용하는 함수는 변경이 없도록 하는 효과를 줄 수 있습니다.

2021-06-01 08:50 UTC, Action2theFuture commented on user/views.py
> +            return JsonResponse({'massege':'create'}, status=200)
프로필 사진을 등록되어있으면 업데이트되게 만들었습니다

2021-06-01 08:55 UTC, Action2theFuture commented on user/views.py
> +            file_urls = f"https://{AWS_S3_CUSTOM_DOMAIN}/profile/{file.name}"
고유한 값으로 수정하겠습니다

2021-06-01 09:09 UTC, Action2theFuture commented on user/views.py
> +            )
처음에 class를 이용하여 멘토님께서 말씀하신 경우로 작성하였지만 오류가 발생하여서 지금의 코드로 수정하였습니다
정확한 이유는 모르겠지만 제 생각으로는 토큰 데코레이터가 self를 공유하는 일이 발생해 그런 일이 생긴 것 같습니다

2021-06-01 09:44 UTC, Action2theFuture commented on user/views.py
> +            )
처음에 멘토님이 말씀하신 것처럼 class로 작성하였으나 오류가 발생하여 수정하였습니다
오류 메세지를 본 개인적인 생각으로는 client의 class의 self와 토큰 데코레이터 클레스의 self와 공유를 하여서 오류가 발생하는 것 같습니다

멘토님의 말씀을 반영하여 업로드 시키는 함수를 만들어서 모듈화시키는 방법을 택했습니다

2021-06-01 13:34 UTC, Kang-kyunghun requested changes

2021-06-01 13:34 UTC, Kang-kyunghun commented on user/views.py
> +    global client
여기서 굳이 global을 사용해야 할까요? class attribute로 지정했으면, class 안에서는 자유롭게 사용할 수 있습니다.

2021-06-01 13:45 UTC, Action2theFuture commented on user/views.py
> +    global client
이것도 위와 동일한 문제인데 global을 사용하지 않고 self.clinet를 하면 토큰 데코레이터와 self과 공유되는 문제로 오류가 발생합니다

2021-06-01 14:07 UTC, Action2theFuture commented
수정 완료

2021-06-02 01:38 UTC, lordmyshepherd commented
https://github.com/wecode-bootcamp-korea/20-2nd-BeerBnB-backend/pull/9#discussion_r642950261 에 대한 답변드리자면,

"오류 메세지를 본 개인적인 생각으로는 client의 class의 self와 토큰 데코레이터 클레스의 self와 공유를 하여서 오류가 발생하는 것 같습니다"
라고 하신 부분은 이상하네요..

상속받지 않는 이상 self를 공유할 수는 없습니다. 아래와 같은 방향성으로 코드를 작성해보신건가요?

```python
class S3Client:
    def __init__(self, s3_client, bucket):
        self.s3_client = s3_client
        self.s3_bucket = bucket

    def upload(self, file):
        file_name = uuid.uuid4()
        self.s3_client.upload_fileobj(
            file,
            self.BUCKET,
            'profile/{file_name}',                
            ExtraArgs={"ContentType": file.content_type}
       )
       return f"https://{AWS_S3_CUSTOM_DOMAIN}/profile/{file_name}" 
```
in View
```python
boto3_s3 = boto3.client(
    's3',
    aws_access_key_id = my_settings.AWS_S3_ACCESS_KEY_ID,
    aws_secret_access_key = my_settings.AWS_S3_SECRET_ACCESS_KEY
)
class Proflie(View):
    def post(self, request):
        s3_client = S3Client(boto3_s3, BUCKET)
        file   = request.FILES.get('profile_file')
        if file:
            storage_path = s3_client.upload(request.file)
        ...
```

2021-06-02 01:39 UTC, lordmyshepherd requested changes

2021-06-02 01:39 UTC, lordmyshepherd commented on user/views.py
> +            return JsonResponse({'massege':'create'}, status=200)
다른 profile image 사진이 들어오게 되면, 기존에 있던 recored에 profile_url이 업데이트되는게 아니라 새로운 객체를 만들 것 같아요!
(참고) https://docs.djangoproject.com/en/3.2/ref/models/querysets/
(참고) https://docs.djangoproject.com/en/3.2/ref/models/querysets/#django.db.models.query.QuerySet.get_or_create

그래서 update와 create은 view 자체를 나누는게 좋을 것 같아요! handler method 역할도 더 명확해지구요!

2021-06-02 03:58 UTC, Action2theFuture commented
수정 완료

2021-06-02 05:51 UTC, lordmyshepherd requested changes

2021-06-02 05:51 UTC, lordmyshepherd commented on user/views.py
> +            )
거의 다 왔습니다!! boto3 client 변수 선언하는 부분만 class 밖으로 꺼내면 더 좋을 것 같아요!
`ProfileUpload`과 `ProfileUploadUpdate`에서 같이 사용할 수 있도록이요!
```suggestion
client = boto3.client(...)
class Profile ..

class ...
```

2021-06-02 06:01 UTC, Action2theFuture commented
수정 완료

2021-06-02 07:26 UTC, lordmyshepherd requested changes

2021-06-02 07:26 UTC, lordmyshepherd commented on user/views.py
> +            return JsonResponse({'massege':'create'}, status=200)
```suggestion
            user       = request.user
            s3_client  = S3Client(client)
            file       = request.FILES.get('profile_file')

            if not file:
                return JsonResponse({'massage':"none file"}, status=404)
               
            user.profile_url = s3_client.upload(file)            
            user.save()
            
            return JsonResponse({'massege':'create'}, status=200)
```

2021-06-02 07:26 UTC, lordmyshepherd commented on user/views.py
> +            return JsonResponse({'massege':'create'}, status=200)
나중에는 S3Client의 upload함수가 s3_storage_path를 바로 반환하도록 수정해보면 더욱 가독성이 좋아질 것 같네요. (참고만 해주세요~)

2021-06-02 07:26 UTC, lordmyshepherd commented on user/views.py
> +            #     return JsonResponse({'message': 'UNAUTHORIZED_USER'}, status=401)
주석이 추가된 이유는 뭔가요?

2021-06-02 07:26 UTC, lordmyshepherd commented on user/views.py
> +            #     return JsonResponse({'message': 'UNAUTHORIZED_USER'}, status=401)
이부분만 확인되면 merge 할 수 있을 것 같아요!

2021-06-02 07:29 UTC, Action2theFuture commented on user/views.py
> +            #     return JsonResponse({'message': 'UNAUTHORIZED_USER'}, status=401)
회원가입 후 이메일 인증을 통해 해당 계정을 활성화시키는 기능을 구현하였는데 프로젝트 진행상 힘들 것 같습니다
일단 지금은 구현할 수 없는 기능이라 주석으로 처리해놨습니다

2021-06-02 07:33 UTC, lordmyshepherd commented on user/views.py
> +            #     return JsonResponse({'message': 'UNAUTHORIZED_USER'}, status=401)
이런 경우는 나중에 할 일로,  `# TODO` : ...로 표시해주시면 좋아요~

```suggestion
        # TODO : ...로 표시해주시면 좋아요~
            # if not user.is_allowed:
            #     return JsonResponse({'message': 'UNAUTHORIZED_USER'}, status=401)
```

2021-06-02 07:33 UTC, lordmyshepherd commented on user/views.py
> +            #     return JsonResponse({'message': 'UNAUTHORIZED_USER'}, status=401)
고생 많으셨습니다~

2021-06-02 07:33 UTC, lordmyshepherd commented
LGTM 👍 
고생 많으셨습니다!

2021-06-02 07:34 UTC, merged

2021-06-02 07:35 UTC, Action2theFuture commented on user/views.py
> +            return JsonResponse({'massege':'create'}, status=200)
수정했습니다